
package tp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateurImplService", targetNamespace = "http://service.tp/", wsdlLocation = "http://localhost:8081/WSSCalculator?wsdl")
public class CalculateurImplService
    extends Service
{

    private final static URL CALCULATEURIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATEURIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATEURIMPLSERVICE_QNAME = new QName("http://service.tp/", "CalculateurImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WSSCalculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATEURIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATEURIMPLSERVICE_EXCEPTION = e;
    }

    public CalculateurImplService() {
        super(__getWsdlLocation(), CALCULATEURIMPLSERVICE_QNAME);
    }

    public CalculateurImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATEURIMPLSERVICE_QNAME, features);
    }

    public CalculateurImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATEURIMPLSERVICE_QNAME);
    }

    public CalculateurImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATEURIMPLSERVICE_QNAME, features);
    }

    public CalculateurImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateurImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculateur
     */
    @WebEndpoint(name = "CalculateurImplPort")
    public Calculateur getCalculateurImplPort() {
        return super.getPort(new QName("http://service.tp/", "CalculateurImplPort"), Calculateur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculateur
     */
    @WebEndpoint(name = "CalculateurImplPort")
    public Calculateur getCalculateurImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.tp/", "CalculateurImplPort"), Calculateur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATEURIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATEURIMPLSERVICE_EXCEPTION;
        }
        return CALCULATEURIMPLSERVICE_WSDL_LOCATION;
    }

}
